### ISSUE TITLE
dropWhile not work as expected

### ISSUE THREAD

**Issue by ihmcjacky** [documentcloud/underscore-contrib#203]
The "dropWhile" seems not perform it should be done, from the given ex

dropWhile
_.dropWhile([-2,-1,0,1,2], isNeg);
Signature: _.dropWhile(array:Array, pred:Function)
//=> [0,1,2]
But when the input is _.dropWhile([0,1,2,-2,-1], isNeg);
The result becomes [0, 1, 2, -2, -1]

**Comment by reefdog** [comment]
With the caveat that I don't know the history of `dropWhile()`: it looks like its intent is to iterate over the array, dropping items that evaluate true when passed to the predicate function, **until** it reaches one that evals falsey, at which point it **returns the rest of the array** regardless of the contents. In which case it's acting as expected.

So basically:

```
_.dropWhile([0,1,-1], isNeg);
//=> [0,1,-1]
_.dropWhile([-1,0,1], isNeg);
//=> [0,1]
_.dropWhile([0,-1,1], isNeg);
//=> [0,-1,1]
_.dropWhile([-2,-1,0], isNeg);
//=> [0]
```

Perhaps you expect it to work like Underscore's [native `reject()`](http://underscorejs.org/#reject)? This is what reject would return (which seems to be what you want):

```
_.reject([0,1,-1], isNeg);
//=> [0,1]
_.reject([-1,0,1], isNeg);
//=> [0,1]
_.reject([0,-1,1], isNeg);
//=> [0,1]
_.reject([-2,-1,0], isNeg);
//=> [0]
```

Certainly the documentation description of `dropWhile()` could use some clarification, since as written it implies behavior identical to `reject()`.

**Comment by ihmcjacky** [comment]
Thanks for the clarification, I seem misunderstand the description of the doc of "dropWhil", sorry for my fault and appreciate for the clarification

**Comment by reefdog** [comment]
@ihmcjacky No prob! The description is a bit confusing.
